config/routes.rb
Rails.application.routes.draw do
    # scope ":locale" do 
        put "/blueprits/filter_update", to: "blueprints#filter_update", as: :filter_update

        get '/calendar', to: 'calendar#index'
        get 'static_pages/home'
        resources :events
        resources :components
        resources :quests
        resources :workers
        resources :blueprints
        resources :languages, only: [:update]
        root to: "static_pages#home" #, as: :localized_root #localized_root_path

    # end 
    # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

    # Defines the root path route ("/")
    # root "articles#index"
    # root to: redirect("/#{I18n.locale}", status: 302)

end

app/models/quest.rb
class Quest < ApplicationRecord
end

app/controllers/quests_controller.rb
class QuestsController < ApplicationController
  before_action :set_quest, only: %i[ show edit update destroy ]

  # GET /quests or /quests.json
  def index
    @quests = Quest.all
  end

  # GET /quests/1 or /quests/1.json
  def show
  end

  # GET /quests/new
  def new
    @quest = Quest.new
  end

  # GET /quests/1/edit
  def edit
  end

  # POST /quests or /quests.json
  def create
    @quest = Quest.new(quest_params)

    respond_to do |format|
      if @quest.save
        format.html { redirect_to quest_url(@quest), notice: "Quest was successfully created." }
        format.json { render :show, status: :created, location: @quest }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @quest.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /quests/1 or /quests/1.json
  def update
    respond_to do |format|
      if @quest.update(quest_params)
        format.html { redirect_to quest_url(@quest), notice: "Quest was successfully updated." }
        format.json { render :show, status: :ok, location: @quest }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @quest.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /quests/1 or /quests/1.json
  def destroy
    @quest.destroy

    respond_to do |format|
      format.html { redirect_to quests_url, notice: "Quest was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_quest
      @quest = Quest.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def quest_params
      params.fetch(:quest, {})
    end
end

app/helpers/quests_helper.rb
module QuestsHelper
end

app/views/quests/_form.html.erb
<%= form_with(model: quest) do |form| %>
  <% if quest.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(quest.errors.count, "error") %> prohibited this quest from being saved:</h2>

      <ul>
        <% quest.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/quests/_quest.html.erb
<div id="<%= dom_id quest %>">
</div>

app/views/quests/edit.html.erb
<h1>Editing quest</h1>

<%= render "form", quest: @quest %>

<br>

<div>
  <%= link_to "Show this quest", @quest %> |
  <%= link_to "Back to quests", quests_path %>
</div>

app/views/quests/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Quests</h1>

<div id="quests">
  <% @quests.each do |quest| %>
    <%= render quest %>
    <p>
      <%= link_to "Show this quest", quest %>
    </p>
  <% end %>
</div>

<%= link_to "New quest", new_quest_path %>

app/views/quests/new.html.erb
<h1>New quest</h1>

<%= render "form", quest: @quest %>

<br>

<div>
  <%= link_to "Back to quests", quests_path %>
</div>

app/views/quests/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @quest %>

<div>
  <%= link_to "Edit this quest", edit_quest_path(@quest) %> |
  <%= link_to "Back to quests", quests_path %>

  <%= button_to "Destroy this quest", @quest, method: :delete %>
</div>