config/routes.rb
Rails.application.routes.draw do
    # scope ":locale" do 
        put "/blueprits/filter_update", to: "blueprints#filter_update", as: :filter_update

        get '/calendar', to: 'calendar#index'
        get 'static_pages/home'
        resources :events
        resources :components
        resources :quests
        resources :workers
        resources :blueprints
        resources :languages, only: [:update]
        root to: "static_pages#home" #, as: :localized_root #localized_root_path

    # end 
    # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

    # Defines the root path route ("/")
    # root "articles#index"
    # root to: redirect("/#{I18n.locale}", status: 302)

end

app/models/blueprint.rb
class Blueprint < ApplicationRecord

    def name
        if I18n.locale == :zh && self.name_zh != nil
            self.name_zh
        else
            self.name_en
        end
    end
end

app/controllers/blueprints_controller.rb
class BlueprintsController < ApplicationController
  before_action :set_blueprint, only: %i[ show edit update destroy ]
  before_action :set_filters,   only: %i[ index show filter_update]

  # GET /blueprints or /blueprints.json
  def index
    @blueprints = Blueprint.all 
  end

  # GET /blueprints/1 or /blueprints/1.json
  def show
  end

  # GET /blueprints/new
  def new
    @blueprint = Blueprint.new
  end

  # GET /blueprints/1/edit
  def edit
  end

  # POST /blueprints or /blueprints.json
  def create
    @blueprint = Blueprint.new(blueprint_params)

    respond_to do |format|
      if @blueprint.save
        format.html { redirect_to blueprint_url(@blueprint), notice: "Blueprint was successfully created." }
        format.json { render :show, status: :created, location: @blueprint }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @blueprint.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /blueprints/1 or /blueprints/1.json
  def update
    respond_to do |format|
      if @blueprint.update(blueprint_params)
        format.html { redirect_to blueprint_url(@blueprint), notice: "Blueprint was successfully updated." }
        format.json { render :show, status: :ok, location: @blueprint }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @blueprint.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /blueprints/1 or /blueprints/1.json
  def destroy
    @blueprint.destroy

    respond_to do |format|
      format.html { redirect_to blueprints_url, notice: "Blueprint was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def filter_update
    filter = {}
    filter_not = {}

    if params["valid_resource"]
      params["valid_resource"].each do |resource|
        filter_not[resource.to_sym] = nil 
      end
    end

    if params["invalid_resource"]
      params["invalid_resource"].each do |resource|
        filter[resource.to_sym] = nil
      end
    end
    filter[:tier] = params["tier"] 
    filter[:category] = params["category"] 

    @blueprints = Blueprint.where(filter)

    if !filter_not.empty?
      filter_not.each do |key, val|
        @blueprints = @blueprints.where.not(key => val)
      end
    end

    if params[:valid_component].present?
      @blueprints = @blueprints.where("components ?& ARRAY[:keys]", keys: params[:valid_component])
    end

    if params[:invalid_component].present?
      @blueprints = @blueprints.where("NOT (components ?| ARRAY[:excluded_keys])", excluded_keys: params[:invalid_component])
    end

    respond_to do |format|
      format.html { redirect_to blueprints_url}
      format.turbo_stream
    end

  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_blueprint
      @blueprint = Blueprint.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def blueprint_params
      params.fetch(:blueprint, {})
    end

    def set_filters
      @tiers = Blueprint.select(:tier).distinct.pluck(:tier).sort!
      @weapons = ['sword', 'axe', 'dagger', 'mace', 'spear', 'bow', 'wand', 'staff', 'gun', 'crossbow', 'instrument']
      @accessories = ['herbal_medicine', 'potion', 'spell', 'shield', 'ring', 'amulet', 'cloak', 'familiar', 'aurasong','meal', 'dessert']
      @armors = ['heavy_armor', 'light_armor', 'clothes','helmet','rogue_hat', 'magician_hat', 'gauntlets', 'gloves', 'heavy_footwear','light_footwear']
      @other_categories = ['runestone', 'moonstone', 'element', 'spirit']
      @resources = ['iron', 'wood', 'leather', 'herbs', 'steel', 'ironwood', 'fabric', 'oil', 'jewels', 'ether', 'essence']
      @components = Component.pluck(:component_id) << 'stone' << 'precraft'
    end
end

app/helpers/blueprints_helper.rb
module BlueprintsHelper
end

app/views/blueprints/_blueprint.html.erb
<div id="<%= dom_id blueprint %>" class="blueprint">
<h2><%= blueprint.name %></h1>
<%= "T#{blueprint.tier} #{t "categories.#{blueprint.category}"}" %>
<div class="resources_listing">
    <% @resources.each do |resource| %>
        <% resource_val = blueprint.send(resource) %>
        <% if resource_val %>
            <div class="crafting_resource">
                <%= image_tag "resources/#{resource}.png", Alt: resource %>
                <%= resource_val %>
            </div>
        <% end %>
    <% end %>
    <% @components.each do |component| %>
        <% if blueprint.components.key?(component) %>
            <div class="crafting_resource">
                <% if component == 'stone' %>
                    <% comp = blueprint.components[component]['id'] %>
                    <%= image_tag "stones/#{comp}.png", Alt: comp %>
                    <%= blueprint.components[component]['amount'].to_i %>
                <% else %>
                    <%= image_tag "components/#{component}.png", Alt: component %>
                    <%= blueprint.components[component]['amount'].to_i %>
                <% end %>
            </div>
        <% end %>
    <% end %>
</div>
</div>

app/views/blueprints/_filter.html.erb
    <div class="filter_name"><%= t(filter_name) %></div>
    <div class="filter_options">
    <% options.each do |option| %>
        <%= form.check_box filter_target.to_sym, {
            id: "#{filter_target}_#{option}",
            value: option,
            multiple: true,
            onchange: "this.form.requestSubmit();",
            checked: checked
        }, option, nil %>
        <%= form.label "#{filter_target}_#{option}" do %>
            <% if filter_name == 'tier' %>
                <%= image_tag "general/tier_bg.png", alt:"tier#{option}" %>
                <span class="text-overlay"><%= option %></span>
            <% elsif img_url == 'components' && option == 'stone' %>
                <%= image_tag "stones/runestones.png", alt: 'stones' %>
            <% else %>
                <%= image_tag "#{img_url}/#{option}.png", alt: "option" %>
            <% end %>
        <% end %>
    <% end %>
    </div>

app/views/blueprints/_filter_all_none.html.erb
<%= form.button "", class: "select-all-button", data: {target: filter_target} do  %>
    <%= image_tag "general/all.png", alt: "Select All" %>
<% end %>

<%= form.button "", class: "select-none-button", data: {target: filter_target} do %>
    <%= image_tag "general/none.png", alt: "Select None" %>
<% end %>

app/views/blueprints/_filter_container.html.erb
<div id="blueprint_filters">
<%= form_with url: filter_update_path, method: :put do |form| %>
  <nav id="filter-side-bar">
    <ul>
      <li filter-target="tier"> <%= t("tier") %></li>
      <li filter-target="category" class="active"><%= t("category") %></li>
      <li filter-target="resource"><%= t("resource") %></li>
      <li filter-target="components"><%= t("components") %></li>
      <li filter-target="sort_by"><%= t("sort_by") %></li>
    </ul>
  </nav>

  <div class= "filter-container">

    <div class="filter", filter-target="tier">
      <div class="filter-line">
        <%= render partial: 'blueprints/filter', locals: {
          filter_name: 'tier',
          filter_target: 'tier',
          options: @tiers,
          form: form,
          checked: true,
          img_url: nil,
        } %>
        <%= render partial: 'blueprints/filter_all_none', locals: {
          filter_target: 'tier',
          form: form
        } %>
      </div>
    </div>

    <div class="filter active", filter-target="category">
      <div class="filter-line">
        <%= render partial: 'blueprints/filter', locals: {
          filter_target: "category",
          filter_name: 'weapon',
          options: @weapons,
          form: form,
          checked: true,
          img_url: 'categories',
        } %>
      </div>

      <div class="filter-line">
        <%= render partial: 'blueprints/filter', locals: {
          filter_target: "category",
          filter_name: 'armor',
          options: @armors,
          form: form,
          checked: true,
          img_url: 'categories',
        } %>
      </div>

      <div class="filter-line">
        <%= render partial: 'blueprints/filter', locals: {
          filter_target: "category",
          filter_name: 'accessory',
          options: @accessories,
          form: form,
          checked: true,
          img_url: 'categories',
        } %>
      </div>

      <div class="filter-line">
        <%= render partial: 'blueprints/filter', locals: {
          filter_target: "category",
          filter_name: 'other',
          options: @other_categories,
          form: form,
          checked: true,
          img_url: 'categories',
        } %>

        <%= render partial: 'blueprints/filter_all_none', locals: {
          filter_target: 'category',
          form: form
        } %>
      </div>
    </div>
    
    <div class="filter", filter-target="resource">

      <div class="filter-line">
        <%= render partial: 'blueprints/filter', locals: {
          filter_target: "valid_resource",
          filter_name: 'inclusion',
          options: @resources,
          form: form,
          checked: false,
          img_url: 'resources',
        } %>

        <%= render partial: 'blueprints/filter_all_none', locals: {
          filter_target: 'valid_resource',
          form: form
        } %>
      </div>

      <div class="filter-line">
        <%= render partial: 'blueprints/filter', locals: {
          filter_target: "invalid_resource",
          filter_name: 'exclusion',
          options: @resources,
          form: form,
          checked: false,
          img_url: 'resources',
        } %>
        <%= render partial: 'blueprints/filter_all_none', locals: {
          filter_target: 'invalid_resource',
          form: form
        } %>
      </div>
    </div>

    <div class="filter", filter-target="components">
      <div class="filter-line">
        <%= render partial: 'blueprints/filter', locals: {
          filter_target: "valid_component",
          filter_name: 'inclusion',
          options: @components,
          form: form,
          checked: false,
          img_url: 'components',
        } %>

        <%= render partial: 'blueprints/filter_all_none', locals: {
          filter_target: 'valid_component',
          form: form
        } %>
      </div>
      <div class="filter-line">
        <%= render partial: 'blueprints/filter', locals: {
          filter_target: "invalid_component",
          filter_name: 'exclusion',
          options: @components,
          form: form,
          checked: false,
          img_url: 'components',
        } %>

        <%= render partial: 'blueprints/filter_all_none', locals: {
          filter_target: 'invalid_component',
          form: form
        } %>
      </div>
    </div>

    
  </div>

  <% end %>
</div>

app/views/blueprints/_form.html.erb
<%= form_with(model: blueprint) do |form| %>
  <% if blueprint.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(blueprint.errors.count, "error") %> prohibited this blueprint from being saved:</h2>

      <ul>
        <% blueprint.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/blueprints/edit.html.erb
<h1>Editing blueprint</h1>

<%= render "form", blueprint: @blueprint %>

<br>

<div>
  <%= link_to "Show this blueprint", @blueprint %> |
  <%= link_to "Back to blueprints", blueprints_path %>
</div>

app/views/blueprints/filter_update.turbo_stream.erb
<%= turbo_stream.update "blueprints" do %>
    <% @blueprints.each do |blueprint| %>
        <%= link_to(blueprint) do %>
            <%= render blueprint %>
        <% end %>
    <% end %>
<% end %>

app/views/blueprints/index.html.erb
<p class="hidden" style="color: green"><%= notice %></p>

<h1><%= t('navigation.blueprints') %></h1>

<%= render 'blueprints/filter_container' %>

<div id="blueprints">
  <% @blueprints.each do |blueprint| %>
    <%= link_to(blueprint) do %>
      <%= render blueprint %>
    <% end %>
  <% end %>
</div>

<%# link_to "New blueprint", new_blueprint_path %>

app/views/blueprints/new.html.erb
<h1>New blueprint</h1>

<%= render "form", blueprint: @blueprint %>

<br>

<div>
  <%= link_to "Back to blueprints", blueprints_path %>
</div>

app/views/blueprints/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @blueprint %>

<div>
  <%# link_to "Edit this blueprint", edit_blueprint_path(@blueprint) %> |
  <%= link_to "Back to blueprints", blueprints_path %>

  <%# button_to "Destroy this blueprint", @blueprint, method: :delete %>
</div>